from includes.constants import *

class Config:
    DEBUG = DEBUG_MODE
    ENV = ENV
    SECRET_KEY = SECRET_KEY

    HOST = HOST
    PORT = PORT
    SITE_URL = SITE_URL

    LANG = LANG
    TIMEZONE = TIMEZONE

    ENABLE_API_MODE = ENABLE_API_MODE

    UPLOAD_FOLDER = UPLOAD_FOLDER
    ALLOWED_EXTENSIONS = ALLOWED_EXTENSIONS

    ENABLE_LOGGING = ENABLE_LOGGING
    LOG_LEVEL = LOG_LEVEL
